apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: nz0cksr1h-go
  janus-idp.io/tekton: nz0cksr1h-go
  backstage.io/kubernetes-id: nz0cksr1h-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nz0cksr1h-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
